### ISSUE TITLE
wrong import statement in sysinfo.py ?

### ISSUE THREAD

**Issue by linzman** [rtogo/sysinfo#1]
package started working only after i changed 

`from sysinfo.humansize import format_size`
to 
`from humansize import format_size`
in
https://github.com/rtogo/sysinfo/blob/master/sysinfo/sysinfo.py
is it ok?

**Comment by rtogo** [comment]
Yes, it is ok. I did it this way because the humansize lib isn't supposed to be installed. That's why it is imported as sysinfo.humasize.

Are you having any issues using the sysinfo package? How can I help you?

**Comment by linzman** [comment]
nono, everything is ok, good job :)
